name: Build
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '~1.16.2'
      -
        name: Build the package
        run: go build ./...
      -
        name: Test the package
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
