name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '~1.16.2'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
